# Generated by Django 3.2.12 on 2022-04-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='core/images', verbose_name='Логотип')),
                ('banner', models.ImageField(blank=True, upload_to='core/images', verbose_name='Баннер')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Статические данные сайта',
                'verbose_name_plural': 'Статические данные сайта',
            },
        ),
    ]
