# Generated by Django 3.2.12 on 2022-02-26 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('video', models.URLField(blank=True, verbose_name='Видео объекта')),
                ('prepayment', models.CharField(blank=True, max_length=10, verbose_name='Предоплата')),
                ('free_cancel', models.CharField(blank=True, max_length=100, verbose_name='Условия бесплатной отмены брони')),
                ('early_booking_discount', models.IntegerField(blank=True, null=True, verbose_name='Скидка на раннее бронирование')),
                ('requisites', models.TextField(blank=True, verbose_name='Реквизиты')),
                ('prepayments_term', models.BooleanField(default=0, verbose_name='Без предоплаты')),
                ('minimum', models.ImageField(blank=True, upload_to='', verbose_name='Минимальный срок проживания в сутках')),
                ('chek_in', models.TimeField(blank=True, verbose_name='Время заселения')),
                ('chek_out', models.TimeField(blank=True, verbose_name='Время выезда')),
                ('pets', models.BooleanField(default=0, verbose_name='Животные')),
                ('child', models.BooleanField(default=0, verbose_name='Дети')),
                ('another_rules', models.TextField(blank=True, verbose_name='Другие правила')),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.beach', verbose_name='Пляж')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Обьекты размещения',
                'verbose_name_plural': 'Объект размещения',
            },
        ),
        migrations.CreateModel(
            name='Hotel_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('photo', models.FileField(upload_to='images/contacts', verbose_name='Фотография')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('skype', models.BooleanField(default=0)),
                ('whatsapp', models.BooleanField(default=0)),
                ('telegram', models.BooleanField(default=0)),
                ('viber', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('on', models.BooleanField(default=0, verbose_name='Включить')),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('room_number', models.IntegerField(blank=True, null=True, verbose_name='Количество комнат')),
                ('sleep_place', models.IntegerField(blank=True, null=True, verbose_name='Количество спальных мест')),
                ('room_square', models.IntegerField(blank=True, null=True, verbose_name='Площадь комнаты')),
                ('additional_palces', models.IntegerField(blank=True, null=True, verbose_name='Дополнительные места')),
                ('furniture', models.TextField(blank=True, verbose_name='Мебель')),
            ],
            options={
                'verbose_name': 'Номера',
                'verbose_name_plural': 'Номер',
            },
        ),
        migrations.CreateModel(
            name='Number_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('on', models.BooleanField(default=0, verbose_name='Включить')),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_on_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/hotel_photo', verbose_name='Изображение')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_in_filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/hotel_photo_thumb', verbose_name='Изображение')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Number_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/numbers', verbose_name='Изображение')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.number')),
            ],
        ),
        migrations.AddField(
            model_name='number',
            name='options',
            field=models.ManyToManyField(to='core.Number_option', verbose_name='Опции'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel_contact', verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.type_of_object', verbose_name='Тип объекта'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='options',
            field=models.ManyToManyField(to='core.Hotel_option', verbose_name='Опции'),
        ),
    ]
