# Generated by Django 3.2.12 on 2022-02-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo_in_filter',
            options={'verbose_name': 'Фотографию', 'verbose_name_plural': 'Фотографии объекта для страниц фильтрации'},
        ),
        migrations.AlterModelOptions(
            name='photo_on_detail',
            options={'verbose_name': 'Фотографию', 'verbose_name_plural': 'Фотографии объекта для страницы объекта'},
        ),
        migrations.AlterField(
            model_name='hotel',
            name='minimum',
            field=models.IntegerField(blank=True, verbose_name='Минимальный срок проживания в сутках'),
        ),
    ]
