# Generated by Django 3.2.12 on 2022-03-08 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(limit_choices_to={'is_city': True}, on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Город'),
        ),
    ]
