# Generated by Django 3.2.12 on 2022-02-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220226_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.hotel', verbose_name='Отель'),
        ),
    ]
