# Generated by Django 3.2.12 on 2022-06-07 15:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staticdata_logo_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название страницы')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('meta_title', models.TextField(blank=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета описание')),
                ('content_1', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текстовый блок №1')),
                ('content_2', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текстовый блок №2')),
                ('template', models.CharField(choices=[('home.html', 'Главная'), ('contact.html', 'Контакты'), ('about.html', 'О компании')], max_length=12, verbose_name='Шаблон страницы')),
            ],
            options={
                'verbose_name': 'Страницу',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
