# Generated by Django 3.2.12 on 2022-06-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='h1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок H1'),
        ),
    ]
