# Generated by Django 3.2.12 on 2022-02-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_number_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(default='1', unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='number',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
