# Generated by Django 3.2.12 on 2022-06-08 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_page_h1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='template',
        ),
    ]
