# Generated by Django 3.2.12 on 2022-06-08 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_page_template'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
