# Generated by Django 3.2.12 on 2023-06-19 15:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название страницы')),
                ('h1', models.CharField(blank=True, max_length=50, verbose_name='Заголовок H1')),
                ('content_1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текстовый блок №1')),
            ],
            options={
                'verbose_name': 'Обработчик исключений',
                'verbose_name_plural': 'Обработчики исключений',
            },
        ),
    ]
