# Generated by Django 3.2.12 on 2023-06-19 15:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_statuscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscode',
            name='header_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст под заголовком'),
        ),
        migrations.AlterField(
            model_name='statuscode',
            name='content_1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текстовый блок'),
        ),
    ]
