# Generated by Django 3.2.12 on 2023-06-21 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20230619_2138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusCode',
        ),
    ]
