# Generated by Django 3.2.12 on 2023-06-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_delete_statuscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_view',
            field=models.BooleanField(default=True, verbose_name='Отображать в меню'),
        ),
    ]
