# Generated by Django 3.2.12 on 2023-06-21 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_applicationforregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationForRegistration',
        ),
    ]
