# Generated by Django 3.2.12 on 2023-06-09 12:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0083_alter_hotel_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2023, 6, 9), verbose_name='Дата начала')),
                ('end_date', models.DateField(default=datetime.date(2023, 6, 9), verbose_name='Дата окончания')),
                ('people_count', models.IntegerField(default=2, verbose_name='Количество гостей')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Бронирования',
                'verbose_name_plural': 'Бронирование',
            },
        ),
    ]
