# Generated by Django 3.2.12 on 2023-06-09 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20230609_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 9, 12, 4, 40, 300437, tzinfo=utc), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 9, 12, 4, 40, 300423, tzinfo=utc), verbose_name='Дата начала'),
        ),
    ]
