# Generated by Django 3.2.12 on 2023-06-09 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20230609_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
    ]
