# Generated by Django 3.2.12 on 2022-04-12 15:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0044_auto_20220409_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('born', models.DateField(default=datetime.datetime.now, verbose_name='Дата создания')),
                ('period', models.CharField(max_length=50, verbose_name='Период отдыха')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='5', verbose_name='Рейтинг')),
                ('body', models.TextField(verbose_name='Описание')),
                ('email', models.EmailField(max_length=254)),
                ('verificated', models.BooleanField(default=False, verbose_name='Активен')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': '    Отзывы',
            },
        ),
    ]
