# Generated by Django 3.2.12 on 2022-03-11 11:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('is_city', models.BooleanField(default=False, verbose_name='Если город, то ставь галочку!')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный курорт')),
                ('image', models.FileField(upload_to='region', verbose_name='Изображение')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='region.region', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': ' Направления',
            },
        ),
        migrations.CreateModel(
            name='GalleryForRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/region', verbose_name='Изображение')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Фотографию',
                'verbose_name_plural': 'Галерея для региона',
            },
        ),
    ]
