# Generated by Django 3.2.12 on 2022-03-08 20:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_hotel_city'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryforcity',
            name='city',
        ),
        migrations.AddField(
            model_name='region',
            name='is_city',
            field=models.BooleanField(default=False, verbose_name='Если город, то ставь галочку!'),
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='GalleryForCity',
        ),
    ]
