# Generated by Django 3.2.12 on 2022-03-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='is_most_interesting',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной в первом блоке'),
        ),
    ]
