# Generated by Django 3.2.12 on 2022-03-08 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_auto_20220308_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный курорт'),
        ),
        migrations.AlterField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='region.region', verbose_name='Родитель'),
        ),
    ]
