# Generated by Django 3.2.12 on 2022-03-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_region_is_most_interesting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Показывать в блоке популярные на главной'),
        ),
    ]
