# Generated by Django 3.2.12 on 2022-03-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_alter_region_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='season',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Задайте сезон, например(январь-февраль)'),
        ),
    ]
