# Generated by Django 3.2.12 on 2022-06-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0007_auto_20220531_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='h1_title',
        ),
        migrations.RemoveField(
            model_name='region',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='region',
            name='meta_title',
        ),
    ]
