# Generated by Django 3.2.12 on 2022-06-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0008_auto_20220629_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='description',
        ),
    ]
