# Generated by Django 3.2.12 on 2022-03-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='minimum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальный срок проживания в сутках'),
        ),
    ]
