# Generated by Django 3.2.12 on 2022-03-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotel_minimum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='chek_in',
            field=models.TimeField(blank=True, null=True, verbose_name='Время заселения'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='chek_out',
            field=models.TimeField(blank=True, null=True, verbose_name='Время выезда'),
        ),
    ]
