# Generated by Django 3.2.12 on 2022-03-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='slug',
        ),
    ]
