# Generated by Django 3.2.12 on 2022-03-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_hotel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='slug',
        ),
    ]
