# Generated by Django 3.2.12 on 2022-03-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_number_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo_in_filter',
            new_name='HotelPhoto',
        ),
        migrations.DeleteModel(
            name='Photo_on_detail',
        ),
    ]
