# Generated by Django 3.2.12 on 2022-03-20 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_auto_20220320_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelphoto',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='hotelphoto',
            name='image',
            field=models.ImageField(default='profile_image/none/no-img.png', null=True, upload_to='images/hotel_photo_thumb', verbose_name='Изображение'),
        ),
    ]
