# Generated by Django 3.2.12 on 2022-03-20 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20220320_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='object_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.type_of_object', verbose_name='Тип объекта'),
        ),
    ]
