# Generated by Django 3.2.12 on 2022-03-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_hotel_object_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel_contact',
            new_name='HotelContact',
        ),
        migrations.RenameModel(
            old_name='Type_of_Object',
            new_name='HotelOption',
        ),
        migrations.RenameModel(
            old_name='Number_option',
            new_name='NumberOption',
        ),
        migrations.RenameModel(
            old_name='Hotel_option',
            new_name='TypeofObject',
        ),
        migrations.AlterModelOptions(
            name='hoteloption',
            options={'verbose_name': 'Опцию', 'verbose_name_plural': ' Опции для гостиниц'},
        ),
        migrations.AlterModelOptions(
            name='typeofobject',
            options={'verbose_name': 'Тип', 'verbose_name_plural': ' Типы объектов размещения'},
        ),
    ]
