# Generated by Django 3.2.12 on 2022-03-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_auto_20220320_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='contact',
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact',
            field=models.ManyToManyField(blank=True, null=True, to='hotel.HotelContact', verbose_name='Контакты'),
        ),
    ]
