# Generated by Django 3.2.12 on 2022-03-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_auto_20220320_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelcontact',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='images/contacts', verbose_name='Фотография'),
        ),
    ]
