# Generated by Django 3.2.12 on 2022-03-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_alter_hotelcontact_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='contact',
        ),
        migrations.AddField(
            model_name='hotelcontact',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Гостиница'),
        ),
    ]
