# Generated by Django 3.2.12 on 2022-03-20 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_auto_20220320_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='another_rules',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='chek_in',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='chek_out',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='child',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='early_booking_discount',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='free_cancel',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='minimum',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='pets',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='prepayment',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='prepayments_term',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='requisites',
        ),
        migrations.CreateModel(
            name='HotelRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepayment', models.CharField(blank=True, max_length=10, verbose_name='Предоплата')),
                ('free_cancel', models.CharField(blank=True, max_length=100, verbose_name='Условия бесплатной отмены брони')),
                ('early_booking_discount', models.IntegerField(blank=True, null=True, verbose_name='Скидка на раннее бронирование')),
                ('requisites', models.TextField(blank=True, verbose_name='Реквизиты')),
                ('prepayments_term', models.BooleanField(default=0, verbose_name='Без предоплаты')),
                ('minimum', models.IntegerField(blank=True, null=True, verbose_name='Минимальный срок проживания в сутках')),
                ('chek_in', models.TimeField(blank=True, null=True, verbose_name='Время заселения')),
                ('chek_out', models.TimeField(blank=True, null=True, verbose_name='Время выезда')),
                ('pets', models.BooleanField(default=0, verbose_name='Животные')),
                ('child', models.BooleanField(default=0, verbose_name='Дети')),
                ('another_rules', models.TextField(blank=True, verbose_name='Другие правила')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Гостиница')),
            ],
            options={
                'verbose_name': 'Правила',
                'verbose_name_plural': 'Правила гостиниц',
            },
        ),
    ]
