# Generated by Django 3.2.12 on 2022-03-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_auto_20220320_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='another_rules',
            field=models.TextField(blank=True, verbose_name='Другие правила'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='chek_in',
            field=models.TimeField(blank=True, null=True, verbose_name='Время заселения'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='chek_out',
            field=models.TimeField(blank=True, null=True, verbose_name='Время выезда'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='child',
            field=models.BooleanField(default=0, verbose_name='Дети'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='early_booking_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка на раннее бронирование'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='free_cancel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Условия бесплатной отмены брони'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='minimum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальный срок проживания в сутках'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='pets',
            field=models.BooleanField(default=0, verbose_name='Животные'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='prepayment',
            field=models.CharField(blank=True, max_length=10, verbose_name='Предоплата'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='prepayments_term',
            field=models.BooleanField(default=0, verbose_name='Без предоплаты'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='requisites',
            field=models.TextField(blank=True, verbose_name='Реквизиты'),
        ),
        migrations.DeleteModel(
            name='HotelRule',
        ),
    ]
