# Generated by Django 3.2.12 on 2022-03-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_auto_20220322_0012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Number_photo',
            new_name='NumberPhoto',
        ),
    ]
