# Generated by Django 3.2.12 on 2022-03-25 14:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_rename_number_photo_numberphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='video',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео объекта'),
        ),
        migrations.AlterField(
            model_name='number',
            name='furniture',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Мебель'),
        ),
    ]
