# Generated by Django 3.2.12 on 2022-03-25 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_auto_20220325_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('time', models.IntegerField(verbose_name='Время')),
                ('method', models.CharField(choices=[('walk', 'Пешком'), ('avto', 'На авто')], default=1, max_length=10, verbose_name='Метод')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Гостиница')),
            ],
            options={
                'verbose_name': 'Расстояние до обьекта',
                'verbose_name_plural': 'Расстояния до объектов',
            },
        ),
    ]
