# Generated by Django 3.2.12 on 2022-03-25 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distance',
            name='method',
        ),
        migrations.RemoveField(
            model_name='distance',
            name='time',
        ),
        migrations.CreateModel(
            name='DistanceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(verbose_name='Время')),
                ('method', models.CharField(choices=[('walk', 'Пешком'), ('avto', 'На авто')], default=1, max_length=10, verbose_name='Метод')),
                ('distance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.distance', verbose_name='Объект расстояния')),
            ],
            options={
                'verbose_name': 'Время до обьекта',
                'verbose_name_plural': 'Время до объектов',
            },
        ),
    ]
