# Generated by Django 3.2.12 on 2022-03-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_auto_20220325_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distance',
            name='hotel',
        ),
        migrations.AddField(
            model_name='distance',
            name='hotel',
            field=models.ManyToManyField(to='hotel.Hotel', verbose_name='Гостиница'),
        ),
    ]
