# Generated by Django 3.2.12 on 2022-03-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_auto_20220325_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='hotel',
            field=models.ManyToManyField(blank=True, null=True, to='hotel.Hotel', verbose_name='Гостиница'),
        ),
    ]
