# Generated by Django 3.2.12 on 2022-03-27 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_alter_distance_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес (без указания города)'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='child',
            field=models.BooleanField(default=0, verbose_name='Размещение детей'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='object_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.typeofobject', verbose_name='Тип жилья'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='pets',
            field=models.BooleanField(default=0, verbose_name='Размещение животных'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='prepayment',
            field=models.CharField(blank=True, max_length=10, verbose_name='Размер предоплаты в % или в сутках проживания'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='remoteness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Расстояние до моря'),
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('period', models.CharField(max_length=100, verbose_name='Период отдыха')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
