# Generated by Django 3.2.12 on 2022-03-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_auto_20220327_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, to='hotel.HotelOption', verbose_name='Опции'),
        ),
    ]
