# Generated by Django 3.2.12 on 2022-03-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_alter_hotel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='method',
            field=models.CharField(choices=[('walk', 'Пешком'), ('avto', 'На авто')], default=1, max_length=10, verbose_name='Метод'),
        ),
        migrations.AddField(
            model_name='distance',
            name='time',
            field=models.IntegerField(default='10', verbose_name='Время'),
        ),
        migrations.DeleteModel(
            name='DistanceTime',
        ),
    ]
