# Generated by Django 3.2.12 on 2022-03-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0026_auto_20220328_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distance',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='distance',
            name='method',
        ),
        migrations.RemoveField(
            model_name='distance',
            name='time',
        ),
        migrations.CreateModel(
            name='DistanceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(blank=True, null=True, verbose_name='Время')),
                ('method', models.CharField(blank=True, choices=[('walk', 'Пешком'), ('avto', 'На авто')], max_length=10, null=True, verbose_name='Метод')),
                ('distance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.distance', verbose_name='Объект расстояния')),
                ('hotel', models.ManyToManyField(blank=True, null=True, to='hotel.Hotel', verbose_name='Гостиница')),
            ],
            options={
                'verbose_name': 'Время до обьекта',
                'verbose_name_plural': 'Время до объектов',
            },
        ),
    ]
