# Generated by Django 3.2.12 on 2022-03-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0028_numberprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberprice',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
