# Generated by Django 3.2.12 on 2022-04-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0031_auto_20220331_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofobject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel/hoteltype', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='hotelcontact',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='hotel/contacts', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='hotelphoto',
            name='image',
            field=models.ImageField(default='profile_image/none/no-img.png', null=True, upload_to='hotel/hotel_photo_thumb', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='numberphoto',
            name='image',
            field=models.ImageField(upload_to='hotel/numbers', verbose_name='Изображение'),
        ),
    ]
