# Generated by Django 3.2.12 on 2022-04-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0032_auto_20220401_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='premium',
            field=models.BooleanField(default=False, verbose_name='Премиум гостиница'),
        ),
    ]
