# Generated by Django 3.2.12 on 2022-04-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0035_auto_20220405_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteloption',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Класс иконки font-awesome'),
        ),
    ]
