# Generated by Django 3.2.12 on 2022-04-08 15:22

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0036_hoteloption_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63),
        ),
    ]
