# Generated by Django 3.2.12 on 2022-04-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0037_hotel_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
        migrations.AddField(
            model_name='hotelreview',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Откуда вы'),
        ),
    ]
