# Generated by Django 3.2.12 on 2022-04-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0038_auto_20220408_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='distance',
            field=models.ManyToManyField(through='hotel.DistanceTime', to='hotel.Distance'),
        ),
        migrations.RemoveField(
            model_name='distancetime',
            name='hotel',
        ),
        migrations.AddField(
            model_name='distancetime',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Гостиница'),
        ),
    ]
