# Generated by Django 3.2.12 on 2022-04-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0039_auto_20220409_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numberprice',
            old_name='finish',
            new_name='period_finish',
        ),
        migrations.RenameField(
            model_name='numberprice',
            old_name='start',
            new_name='period_start',
        ),
        migrations.AddField(
            model_name='numberprice',
            name='dop_place',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена доп места'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='beach',
            field=models.CharField(choices=[('galka', 'Галька'), ('pesok', 'Песок')], default=1, max_length=50, verbose_name='Пляж'),
        ),
        migrations.DeleteModel(
            name='Beach',
        ),
    ]
