# Generated by Django 3.2.12 on 2022-04-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0043_auto_20220409_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='price_period',
        ),
        migrations.RemoveField(
            model_name='priceperiod',
            name='number_price',
        ),
    ]
