# Generated by Django 3.2.12 on 2022-04-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0044_auto_20220409_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelReview',
        ),
    ]
