# Generated by Django 3.2.12 on 2022-04-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0046_alter_hotel_remoteness'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteloption',
            name='comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='remoteness',
            field=models.IntegerField(blank=True, choices=[(100, '100'), (200, '200'), (500, '500'), (800, '800'), (1000, '1000'), (1500, '1500')], default=1, null=True, verbose_name='Расстояние до моря'),
        ),
    ]
