# Generated by Django 3.2.12 on 2022-05-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0047_auto_20220424_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofobject',
            name='slug',
            field=models.SlugField(default='default', verbose_name='URL'),
        ),
    ]
