# Generated by Django 3.2.12 on 2022-05-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0048_typeofobject_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofobject',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
