# Generated by Django 3.2.12 on 2022-06-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0049_alter_typeofobject_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='object_type',
        ),
        migrations.AddField(
            model_name='hotel',
            name='object_type',
            field=models.ManyToManyField(null=True, to='hotel.TypeofObject', verbose_name='Тип жилья'),
        ),
    ]
