# Generated by Django 3.2.12 on 2022-06-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0050_auto_20220621_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='beach',
            field=models.CharField(blank=True, choices=[('galka', 'Галька'), ('pesok', 'Песок')], default=1, max_length=50, verbose_name='Пляж'),
        ),
    ]
