# Generated by Django 3.2.12 on 2022-06-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0053_alter_hotel_remoteness'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFilterofObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel/filterservice', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Критерий удобства',
                'verbose_name_plural': ' Критерии удобства',
            },
        ),
        migrations.AlterField(
            model_name='hotel',
            name='object_type',
            field=models.ManyToManyField(blank=True, to='hotel.TypeofObject', verbose_name='Тип жилья'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='object_service',
            field=models.ManyToManyField(blank=True, to='hotel.ServiceFilterofObject', verbose_name='Фильтр по критериям жилья'),
        ),
    ]
