# Generated by Django 3.2.12 on 2022-06-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0054_auto_20220626_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='remoteness',
            field=models.IntegerField(blank=True, choices=[(100, '100'), (200, '200'), (500, '500'), (800, '800'), (1000, '1000'), (1500, '1500')], default=1, verbose_name='Расстояние до моря'),
        ),
    ]
