# Generated by Django 3.2.12 on 2022-07-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0058_alter_hotel_remoteness'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='extra_bed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена за дополнительное место'),
        ),
    ]
