# Generated by Django 3.2.12 on 2022-07-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0059_price_extra_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='order_choice',
            field=models.CharField(choices=[('number', 'за номер'), ('people', 'за человека')], default=1, max_length=10, verbose_name='За номер или за человека'),
        ),
    ]
