# Generated by Django 3.2.12 on 2022-07-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0061_auto_20220723_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='order_choice',
            field=models.CharField(choices=[('number', 'за номер'), ('people', 'за человека')], default='за номер', max_length=10, verbose_name='Цена в объявлении'),
        ),
    ]
