# Generated by Django 3.2.12 on 2022-07-23 15:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0062_alter_number_order_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='add_information',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Дополнительная информация'),
        ),
    ]
