# Generated by Django 3.2.12 on 2022-07-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0063_number_add_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='add_information',
        ),
    ]
