# Generated by Django 3.2.12 on 2022-07-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0064_remove_number_add_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='beach',
            field=models.CharField(blank=True, choices=[('galka', 'Галька'), ('pesok', 'Песок')], default='1000', max_length=50, verbose_name='Пляж'),
        ),
    ]
