# Generated by Django 3.2.12 on 2022-07-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0065_alter_hotel_beach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='remoteness',
            field=models.IntegerField(blank=True, choices=[('1', '100'), ('2', '200'), ('5', '500'), ('8', '800'), ('10', '1000'), ('15', '1500')], default=1, verbose_name='Расстояние до моря'),
        ),
    ]
