# Generated by Django 3.2.12 on 2022-07-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0066_alter_hotel_remoteness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='remoteness',
            field=models.CharField(blank=True, choices=[('100', '100'), ('200', '200'), ('500', '500'), ('800', '800'), ('1000', '1000'), ('1500', '1500')], default=1, max_length=10, verbose_name='Расстояние до моря'),
        ),
    ]
