# Generated by Django 3.2.12 on 2022-07-23 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0067_alter_hotel_remoteness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.number', verbose_name='Номер'),
        ),
    ]
