# Generated by Django 3.2.12 on 2022-07-27 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0069_auto_20220724_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelphoto',
            options={'ordering': ['hotel'], 'verbose_name': 'Фотографию', 'verbose_name_plural': 'Фотографии объекта для страниц фильтрации'},
        ),
        migrations.AlterModelOptions(
            name='priceperiod',
            options={'verbose_name': 'Период цен', 'verbose_name_plural': 'Периоды цен на гостиницы'},
        ),
        migrations.RemoveField(
            model_name='priceperiod',
            name='extra_bed',
        ),
        migrations.RemoveField(
            model_name='priceperiod',
            name='number',
        ),
        migrations.RemoveField(
            model_name='priceperiod',
            name='price',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('extra_bed', models.IntegerField(blank=True, null=True, verbose_name='Цена за дополнительное место')),
                ('number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.number', verbose_name='Номер')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.priceperiod', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Цены',
                'verbose_name_plural': 'Цены гостиницы',
            },
        ),
    ]
