# Generated by Django 3.2.12 on 2022-08-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0070_auto_20220727_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelphoto',
            options={'verbose_name': 'Фотографию', 'verbose_name_plural': 'Фотографии объекта для страниц фильтрации'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['period__start'], 'verbose_name': 'Цены', 'verbose_name_plural': 'Цены гостиницы'},
        ),
        migrations.AlterModelOptions(
            name='priceperiod',
            options={'ordering': ['start'], 'verbose_name': 'Календарные периоды цен', 'verbose_name_plural': 'Период цен'},
        ),
        migrations.AddField(
            model_name='hotel',
            name='centr',
            field=models.CharField(blank=True, max_length=20, verbose_name='Расстояние до центра'),
        ),
    ]
