# Generated by Django 3.2.12 on 2022-08-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0071_auto_20220801_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelphoto',
            options={'ordering': ['id'], 'verbose_name': 'Фотографию', 'verbose_name_plural': 'Фотографии объекта для страниц фильтрации'},
        ),
    ]
