# Generated by Django 3.2.12 on 2022-10-18 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0072_alter_hotelphoto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата публикации'),
        ),
    ]
