# Generated by Django 3.2.12 on 2022-11-10 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0073_hotel_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='hotel.number', verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='price',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='hotel.priceperiod', verbose_name='Период'),
        ),
    ]
