# Generated by Django 3.2.12 on 2022-11-10 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0074_auto_20221110_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceperiod',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='hotel.hotel', verbose_name='Гостиница'),
        ),
    ]
