# Generated by Django 3.2.12 on 2022-11-10 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0075_alter_priceperiod_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='hotel.hotel', verbose_name='Отель'),
        ),
    ]
