# Generated by Django 3.2.12 on 2023-02-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0076_alter_number_hotel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distancetime',
            options={'verbose_name': 'Время до объекта', 'verbose_name_plural': 'Время до объектов'},
        ),
        migrations.AlterField(
            model_name='distancetime',
            name='time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время в минутах'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='distance',
            field=models.ManyToManyField(through='hotel.DistanceTime', to='hotel.Distance', verbose_name='Объекты рядом'),
        ),
    ]
