# Generated by Django 3.2.12 on 2023-02-23 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0077_auto_20230202_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberphoto',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number', to='hotel.number'),
        ),
    ]
