# Generated by Django 3.2.12 on 2023-02-23 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0078_alter_numberphoto_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberphoto',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.number'),
        ),
    ]
