# Generated by Django 3.2.12 on 2023-04-14 15:52

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0080_alter_numberphoto_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Гостиница')),
            ],
            options={
                'verbose_name': ' Отзыв',
                'verbose_name_plural': ' Отзывы',
            },
        ),
    ]
