# Generated by Django 3.2.12 on 2023-04-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0081_hotelreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelReview',
        ),
    ]
