# Generated by Django 3.2.12 on 2023-06-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0083_alter_hotel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofobject',
            name='services',
            field=models.ManyToManyField(blank=True, to='hotel.ServiceFilterofObject', verbose_name='Какие критерии жилья отображать на странице'),
        ),
    ]
