# Generated by Django 3.2.12 on 2023-07-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0084_typeofobject_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='published',
            field=models.BooleanField(default=1, verbose_name='Опубликовать гостиницу'),
        ),
    ]
