# Generated by Django 3.2.12 on 2023-07-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0086_bookmarkhotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='published',
            field=models.BooleanField(default=0, verbose_name='Опубликовать гостиницу'),
        ),
    ]
