# Generated by Django 3.2.12 on 2022-03-11 11:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('thumb', models.FileField(upload_to='images/attraction_thumb', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Достопримечательность',
                'verbose_name_plural': 'Достопримечательности',
            },
        ),
        migrations.CreateModel(
            name='AttractionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория достопримечательности',
                'verbose_name_plural': 'Категории достопримечательностей',
            },
        ),
        migrations.CreateModel(
            name='AttractionGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/attraction', verbose_name='Изображение')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attraction.attraction')),
            ],
            options={
                'verbose_name': 'Фотографию',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.AddField(
            model_name='attraction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attraction.attractioncategory', verbose_name='Категория'),
        ),
    ]
