# Generated by Django 3.2.12 on 2022-04-04 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0006_alter_region_description'),
        ('attraction', '0002_attraction_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='region',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_city': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Курорт'),
        ),
    ]
