# Generated by Django 3.2.12 on 2022-04-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0003_alter_attraction_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Мета описание'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Мета заголовок'),
        ),
    ]
