# Generated by Django 3.2.12 on 2023-06-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userQueries', '0002_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Запрос на обратную связ', 'verbose_name_plural': 'Запросы на обратную связ'},
        ),
        migrations.AddField(
            model_name='applicationforregistration',
            name='name',
            field=models.CharField(default='+7 (000) 000 00 00', max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
