# Generated by Django 3.2.12 on 2023-06-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userQueries', '0004_alter_applicationforregistration_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Запрос на обратную связь', 'verbose_name_plural': 'Запросы на обратную связь'},
        ),
    ]
