# Generated by Django 3.2.12 on 2022-06-08 21:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название страницы')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('h1', models.CharField(blank=True, max_length=50, verbose_name='Заголовок H1')),
                ('meta_title', models.TextField(blank=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета описание')),
                ('content_1', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текстовый блок №1')),
                ('content_2', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текстовый блок №2')),
            ],
            options={
                'verbose_name': 'SEO для страницы',
                'verbose_name_plural': 'SEO для статических страниц',
            },
        ),
    ]
