# Generated by Django 3.2.12 on 2022-06-23 12:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_auto_20220609_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seofortype',
            name='content_1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текстовый блок №1'),
        ),
        migrations.AlterField(
            model_name='seofortype',
            name='content_2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текстовый блок №2'),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='content_1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текстовый блок №1'),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='content_2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текстовый блок №2'),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='slug',
            field=models.SlugField(verbose_name='URL страницы, к которой привязываем'),
        ),
    ]
