# Generated by Django 3.2.12 on 2022-06-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_auto_20220623_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='seopage',
            name='header_text',
            field=models.TextField(blank=True, verbose_name='Текст под заголовком'),
        ),
    ]
