# Generated by Django 3.2.12 on 2022-06-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_seopage_header_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seofortype',
            name='content_2',
        ),
    ]
