# Generated by Django 3.2.12 on 2022-06-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0006_remove_seofortype_content_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='seofortype',
            name='h1',
            field=models.CharField(blank=True, max_length=50, verbose_name='H1 заголовок'),
        ),
    ]
