# Generated by Django 3.2.12 on 2022-06-29 13:44

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0007_auto_20220531_0909'),
        ('seo', '0007_seofortype_h1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seofortype',
            name='content_1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текстовый блок'),
        ),
        migrations.CreateModel(
            name='SeoForRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_alt', models.CharField(blank=True, max_length=50, verbose_name='ALT изображения')),
                ('image_title', models.CharField(blank=True, max_length=50, verbose_name='Title для изображения')),
                ('meta_title', models.TextField(blank=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета описание')),
                ('h1', models.CharField(blank=True, max_length=50, verbose_name='H1 заголовок')),
                ('content_1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текстовый блок')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'SEO для региона',
                'verbose_name_plural': 'SEO для регионов',
            },
        ),
    ]
