# Generated by Django 3.2.12 on 2022-07-01 21:16

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0058_alter_hotel_remoteness'),
        ('region', '0009_remove_region_description'),
        ('seo', '0008_auto_20220629_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoForService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_alt', models.CharField(blank=True, max_length=50, verbose_name='ALT изображения')),
                ('image_title', models.CharField(blank=True, max_length=50, verbose_name='Title для изображения')),
                ('meta_title', models.TextField(blank=True, verbose_name='Мета заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета описание')),
                ('h1', models.CharField(blank=True, max_length=50, verbose_name='H1 заголовок')),
                ('content_1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текстовый блок')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Город')),
                ('service_of_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.servicefilterofobject', verbose_name='Тиж жилья')),
            ],
            options={
                'verbose_name': 'SEO для страницы критерия жилья',
                'verbose_name_plural': 'SEO для страниц критериев жилья',
            },
        ),
    ]
