# Generated by Django 3.2.12 on 2022-07-01 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0058_alter_hotel_remoteness'),
        ('seo', '0009_seoforservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoforservice',
            name='type_of_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.typeofobject', verbose_name='Тиж жилья'),
        ),
        migrations.AlterField(
            model_name='seoforservice',
            name='service_of_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.servicefilterofobject', verbose_name='Критерий жилья'),
        ),
    ]
