# Generated by Django 3.2.12 on 2023-04-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0010_auto_20220702_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seopage',
            name='slug',
            field=models.CharField(max_length=50, verbose_name='URL страницы, к которой привязываем'),
        ),
    ]
