# Generated by Django 3.2.12 on 2023-04-24 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
        ('seo', '0011_alter_seopage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='seopage',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='page.page', verbose_name='Страница к которой привязываем СЕО'),
        ),
    ]
