# Generated by Django 3.2.12 on 2023-04-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0012_seopage_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seopage',
            name='page',
        ),
    ]
