# Generated by Django 3.2.12 on 2023-06-22 19:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0014_auto_20230618_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='seopage',
            name='content_contact',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текстовый блок (Страница контакты)'),
        ),
    ]
